import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faAllergies,
  faAppleWhole,
  faBaby,
  faBacteria,
  faBandage,
  faBedPulse,
  faBolt,
  faBone,
  faBookMedical,
  faBrain,
  faBug,
  faCamera,
  faCapsules,
  faChartBar,
  faChartLine,
  faChild,
  faClipboardCheck,
  faCloudBolt,
  faCommentMedical,
  faCrosshairs,
  faCube,
  faDisease,
  faDna,
  faDroplet,
  faEarListen,
  faEye,
  faEyeLowVision,
  faFaceSmile,
  faFlask,
  faFolder,
  faGavel,
  faGlasses,
  faHand,
  faHandDots,
  faHeadSideVirus,
  faHeartCircleCheck,
  faHeartPulse,
  faHeartbeat,
  faHelmetSafety,
  faHospital,
  faIdCard,
  faLeaf,
  faLungs,
  faMagnifyingGlass,
  faMicrophone,
  faMicroscope,
  faOilCan,
  faPalette,
  faPeopleGroup,
  faPerson,
  faPersonPregnant,
  faPersonRunning,
  faPersonWalking,
  faRadiation,
  faRibbon,
  faScaleBalanced,
  faScissors,
  faSeedling,
  faShieldHeart,
  faShieldVirus,
  faShoePrints,
  faSkull,
  faSkullCrossbones,
  faStethoscope,
  faSyringe,
  faToolbox,
  faTriangleExclamation,
  faTruckMedical,
  faUser,
  faUserDoctor,
  faUsers,
  faVenus,
  faVenusMars,
  faVial,
  faVials,
  faVirus,
  faWind,
  faWineBottle,
  faXRay,
} from "@fortawesome/free-solid-svg-icons";

export const CATEGORY_ICONS = {
  faAllergies,
  faAppleWhole,
  faBaby,
  faBacteria,
  faBandage,
  faBedPulse,
  faBolt,
  faBone,
  faBookMedical,
  faBrain,
  faBug,
  faCamera,
  faCapsules,
  faChartBar,
  faChartLine,
  faChild,
  faClipboardCheck,
  faCloudBolt,
  faCommentMedical,
  faCrosshairs,
  faCube,
  faDisease,
  faDna,
  faDroplet,
  faEarListen,
  faEye,
  faEyeLowVision,
  faFaceSmile,
  faFlask,
  faGavel,
  faGlasses,
  faHand,
  faHandDots,
  faHeadSideVirus,
  faHeartCircleCheck,
  faHeartPulse,
  faHeartbeat,
  faHelmetSafety,
  faHospital,
  faIdCard,
  faLeaf,
  faLungs,
  faMagnifyingGlass,
  faMicrophone,
  faMicroscope,
  faOilCan,
  faPalette,
  faPeopleGroup,
  faPerson,
  faPersonPregnant,
  faPersonRunning,
  faPersonWalking,
  faRadiation,
  faRibbon,
  faScaleBalanced,
  faScissors,
  faSeedling,
  faShieldHeart,
  faShieldVirus,
  faShoePrints,
  faSkull,
  faSkullCrossbones,
  faStethoscope,
  faSyringe,
  faToolbox,
  faTriangleExclamation,
  faTruckMedical,
  faUser,
  faUserDoctor,
  faUsers,
  faVenus,
  faVenusMars,
  faVial,
  faVials,
  faVirus,
  faWind,
  faWineBottle,
  faXRay,
} as const;

export type CategoryIconKey = keyof typeof CATEGORY_ICONS;

export function getCategoryIcon(key?: string | null): IconDefinition {
  if (key && key in CATEGORY_ICONS) {
    return CATEGORY_ICONS[key as CategoryIconKey];
  }
  return faFolder;
}

function iconKeyToLabel(key: string): string {
  return key
    .replace(/^fa/, "")
    .replace(/([A-Z])/g, " $1")
    .trim();
}

export const CATEGORY_ICON_OPTIONS = (
  Object.entries(CATEGORY_ICONS) as [CategoryIconKey, IconDefinition][]
)
  .map(([key, icon]) => ({ key, label: iconKeyToLabel(key), icon }))
  .sort((a, b) => a.label.localeCompare(b.label));
