APPROVED_STATUS = "approved"
PENDING_STATUS = "pending"
REJECTED_STATUS = "rejected"

QUESTION_STATUSES = (
	APPROVED_STATUS,
	PENDING_STATUS,
	REJECTED_STATUS,
)

IN_PROGRESS_STATUS = "in_progress"
SUBMITTED_STATUS = "submitted"
EXPIRED_STATUS = "expired"

SUBMISSION_STATUSES = (
	IN_PROGRESS_STATUS,
	SUBMITTED_STATUS,
	EXPIRED_STATUS,
)