import os
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT", 587)
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# AAILE LAI CHAI BACKEND LAI URL MA SET GAREKO XA, FRONTEND MA SET CHANGE (TODO)
EMAIL_VERIFICATION_URL = os.getenv("EMAIL_VERIFICATION_URL", "http://localhost:8000/verify-email/")
PASSWORD_RESET_URL = os.getenv("PASSWORD_RESET_URL", "http://localhost:8000/reset-password/")
EMAIL_TIMEOUT = 20